config/routes.rb
Rails.application.routes.draw do

  #resources :wishlists
  #resources :carts
  resources :products
  resources :merchants do
    resources :products, only: [:index, :show]
  end
  #resources :customers
  resources :customers do
    resources :products do
      resources :cart_products, only: [:create]
        resources :wishlists, only: [:create]
    end
    resources :cart_products, only: [:index]
    resources :wishlists, only: [:index]
  end
  resources :cart_products
  resources :wishlists
  root "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :set_cart_product, only: [:show, :edit, :update, :destroy]
  before_action :set_post_params, only: [:create]

  # GET /cart_products
  # GET /cart_products.json
  def index
    @cart_products = @customer.cart_products
  end

  # GET /cart_products/1
  # GET /cart_products/1.json
  def show
  end

  # GET /cart_products/new
  def new
    @cart_product = CartProduct.new
  end

  # GET /cart_products/1/edit
  def edit
  end

  def add_cart_product
    @cart_product = CartProduct.new(cart_product_params)
  end

  # POST /cart_products
  # POST /cart_products.json
  def create
    @cart_product = CartProduct.new(set_post_params)

    product = @cart_product.product

    respond_to do |format|
      if @cart_product.save
        format.html { redirect_to merchant_product_path(product.merchant, product), notice: 'Cart product was successfully created.' }
        format.json { render :show, status: :created, location: merchant_product_path(product.merchant, product) }
      else
        format.html { render :new }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_products/1
  # PATCH/PUT /cart_products/1.json
  def update
    respond_to do |format|
      if @cart_product.update(cart_product_params)
        format.html { redirect_to @cart_product, notice: 'Cart product was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_product }
      else
        format.html { render :edit }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_products/1
  # DELETE /cart_products/1.json
  def destroy
    @cart_product.destroy
    respond_to do |format|
      format.html { redirect_to cart_products_url, notice: 'Cart product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_product
      @cart_product = CartProduct.find(params[:id])
    end

    def set_post_params
      params.permit(:customer_id, :product_id)
    end

    # Only allow a list of trusted parameters through.
    def cart_product_params
      params.require(:cart_product).permit(:customer_id, :product_id)
    end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_form.html.erb
<%= form_for(cart_product) do |f| %>
  <% if cart_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_product.errors.count, "error") %> prohibited this cart_product from being saved:</h2>

      <ul>
      <% cart_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_id %>
    <%= f.text_field :cart_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_products/edit.html.erb
<h1>Editing Cart Product</h1>

<%= render 'form', cart_product: @cart_product %>

<%= link_to 'Show', @cart_product %> |
<%= link_to 'Back', cart_products_path %>

app/views/cart_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Products</h1>
<h1>Customer Name: <%= @customer.name %></h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_products.each do |cart_product| %>
      <tr>
        <td><%= cart_product.product.name %></td>
        <td><%= link_to 'Show product', merchant_product_path(cart_product.product.merchant, cart_product.product), {:style=>'background-color:yellow;'} %></td>
        <td><%= link_to 'Remove from Cart', cart_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Go to Merchant List', merchants_path %>

app/views/cart_products/new.html.erb
<h1>New Cart Product</h1>

<%= render 'form', cart_product: @cart_product %>

<%= link_to 'Back', cart_products_path %>

app/views/cart_products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Customer Name: <%= @customer.name %></h1>
<h1>Customer Name: <%= @customer.product.merchant.name %></h1>

<p>
  <strong>Cart:</strong>
  <%= @cart_product.cart %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart_product.product %>
</p>

<%= link_to 'Edit', edit_cart_product_path(@cart_product) %> |
<%= link_to 'Back', cart_products_path %>