config/routes.rb
Rails.application.routes.draw do

  #resources :wishlists
  #resources :carts
  resources :products
  resources :merchants do
    resources :products, only: [:index, :show]
  end
  #resources :customers
  resources :customers do
    resources :products do
      resources :cart_products, only: [:create]
        resources :wishlists, only: [:create]
    end
    resources :cart_products, only: [:index]
    resources :wishlists, only: [:index]
  end
  resources :cart_products
  resources :wishlists
  root "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/merchant.rb
class Merchant < ApplicationRecord
    has_many :products
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def merchant_params
      params.require(:merchant).permit(:name, :address, :email, :website, :about, :phone, :mobile)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_for(merchant) do |f| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<!DOCTYPE html>
<html lang="ar">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DohaSooq - Merchant List</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/css/main.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="ds-no-transition">
<div id="wrapper" style="padding-top: 0px!important">
    <div class="overlay"></div>
    <!-- Sidebar -->
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/header' %>

    <section class="full-width-wrapper bcmp-pgntn-section bg-light-pink">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="sideheading_with_underline">
                        <div class="row">
                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-push-4 col-sm-8 col-xs-12">
                                <div class="row">
                                    <ol class="breadcrumb ds-breadcrumb pull-right">
                                      <li><a href="#">Home</a></li>
<!--                                      <li><a href="#">My Account</a></li>-->
                                      <li class="active">Merchant List</li>
                                    </ol>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-pull-8 col-sm-4 col-xs-12">
                                <h2 class="side_heading">
                                    <span>All Merchant List</span>
                                </h2>
                            </div>
                        </div>
                        <div class="ds-default-line-wrapper"><div class="ds-default-line"></div></div>
                    </div>
                </div>
            </div>

        </div>

    </section>

    <section class="full-width-wrapper bg-light-pink merchant-list">
        <div class="container">
            <div class="row material_form_wrapper">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <form class="search">
                        <div class="form-group pull-right">
                            <label for="search">Search</label>
                            <input type="text" name="Search">
                        </div>
                    </form>
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 merchant-wrapper">
                    <% @merchants.each_slice(2).each do |slices| %>
                    <% slices.each do |merchant| %>
                    <div class="col-md-6 col-sm-6 col-xs-12 pl0">
                        <div class="merchant-list-details">
                            <div class="col-md-5 col-sm-12 col-xs-12 logo_container">
                                <div class="merch-logo">
                                  <img class="menu_icon" height="auto" width="150px" src="<%= merchant.logo %>" />
                                </div>
                            </div>
                            <div class="col-md-7 col-sm-12 col-xs-12 merchant_container">
                                <div class="merch-detail">
                                    <h5><%= merchant.name %></h5>
                                    <div class="contacts">
                                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                                        <p><%= merchant.address %></p>
                                    </div>
                                    <div class="contacts">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                        <p><%= merchant.phone %></p>
                                    </div>
                                    <div class="contacts">
                                        <i class="fa fa-fax" aria-hidden="true"></i>
                                        <p><%= merchant.mobile %></p>
                                    </div>
                                    <div class="contacts">
                                        <i class="fa fa-envelope" aria-hidden="true"></i>
                                        <p><%= merchant.email %></p>
                                    </div>
                                    <div class="contacts">
                                        <i class="fa fa-globe" aria-hidden="true"></i>
                                        <p><%= merchant.website %></p>
                                    </div>
                                    <%= link_to 'Show Products', merchant_products_path(merchant), {:class=>'more-info'}%>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>

                    <%end%>

                </div>
            </div>
        </div>
    </section>
    <%= render 'layouts/footer' %>

</div>
</body>

</html>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @merchant.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @merchant.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @merchant.website %>
</p>

<p>
  <strong>About:</strong>
  <%= @merchant.about %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @merchant.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @merchant.mobile %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>