config/routes.rb
Rails.application.routes.draw do

  #resources :wishlists
  #resources :carts
  resources :products
  resources :merchants do
    resources :products, only: [:index, :show]
  end
  #resources :customers
  resources :customers do
    resources :products do
      resources :cart_products, only: [:create]
        resources :wishlists, only: [:create]
    end
    resources :cart_products, only: [:index]
    resources :wishlists, only: [:index]
  end
  resources :cart_products
  resources :wishlists
  root "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_post_params)

    product = @wishlist.product

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to merchant_product_path(product.merchant, product), notice: 'Wishlist was successfully created.' }
        format.json { render :show, status: :created, location: merchant_product_path(product.merchant, product) }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    def wishlist_post_params
      params.permit(:customer_id, :product_id)
    end

    # Only allow a list of trusted parameters through.
    def wishlist_params
      params.require(:wishlist).permit(:customer_id, :product_id)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_for(wishlist) do |f| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.product.name %></td>
        <td><%= link_to 'Show Product', merchant_product_path(wishlist.product.merchant, wishlist.product) %></td>
        <td><%= link_to 'Remove From Wishlist', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Go to Merchant List', merchants_path %>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @wishlist.customer %>
</p>

<p>
  <strong>Product:</strong>
  <%= @wishlist.product %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>